### ISSUE TITLE
Признаки из текста

### ISSUE THREAD

**Issue by brucebek** [bruciek/texts_attribution#6]
Придумать числовые признаки, которые можно создать из токенов(слова, пунктуация) или предложений.

**Признаки из токенов:**

- частоты чего-то...
- 

**Признаки из предложений**:

-

**Comment by bruciek** [comment]
Результаты мозгового штурама:

1. Частота союза "и";
2. Самое частое слово (по всем, сущ., прилагательное и т.д.);
3. Средняя длина предложений (по словам, по буквам и т.д.);
4. Частота служебных слов (все, союзы и т.д.);
5. Средняя длина слова;
6. Частота знаков препинания (все, запятые и т.д.);
7. Частота определенных букв;
8. Средняя длина служебных слов;
9. Количество слов с большой буквы;
10. Количество слов с заглавной буквы (Количество предложений + );
11. Частота пробелов;
12. Средняя длина абзаца;
13. Частота аббревиатур;
14. Частота слов в начальной форме;
15. Частота использования чисел;
16. Соседство частей речи рядом стоящих слов;
17. Самая частая первая буква;
18. Частота повторений самого часто встречающегося слова в тексте;
19. Средняя позиция в тексте (служебные слова, моды и т.д.), т.е. среднее арифметическое порядковых номеров среди слов;
20. Частота употребления самого длинного слова;
21. Разные отношения количества слов в группах длинных, средних и коротких слов;
22. Среднее арифметическое суммы от двоичного кода (перевод букв 0-1);
23. Во сколько раз больше единиц, чем нулей в двоичном коде (перевод букв 0-1);
24. $\Delta$ 0 и 1 в двоичном коде (перевод букв 0-1);
25. Количество уникальных слов;
26. Количество слов встречающихся по одному разу;
27. $\frac{\sum(\text{частота слов} \cdot \text{длина})}{\text{количество слов}}$;
28. Средняя $\Delta$ длины соседей;
29. Среднее количество слов между запятыми;
30. Отношение количества гласных и согласных букв;
31. Среднее количество слогов в слове (без учета служебных);
32. Средняя длина слов разных частей речи;
33. Среднее количество слогов в разных частях речи;
34. Средняя сумма двоичной записи среди разных частей речи;
35. Средняя сумма двоичной записи гласных и согласных;
36. Склеиваем слова по парам самое частое словосочетание и его средняя длина;
37. Количество слов во множественном числе;
38. Средняя длина текста


Короткие слова (1-4), Средние слова (5-8), Длинные слова(9-...)

**Comment by bruciek** [comment]
```python
def freq_of_word(all_words: list[str], words_for_freq: set[str]) -> float:
    ...
``` 

```python
def freq_of_symbol(text: str, symbols_for_freq: set[str]) -> float:
    ...
``` 

```python
def mode_of_words(words: list[str]) -> str:
    ...
``` 

```python
def find_parts_speech(name_of_part_speech: str) -> list[str]:
    ...
``` 

```python

```
